sonar.projectKey=q1658058197-stack_q1658058197-stack-apache-pdfbox
sonar.organization=q1658058197-stack


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=q1658058197-stack_apache-PDFBOX
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
